import { 
    FiArchive, 
    FiBookOpen, 
    FiBook,
    FiBookmark,
    FiCoffee,
    FiFilm,
    FiHeadphones,
    FiHeart,
    FiLock,
    FiShoppingBag,
    FiShoppingCart,
    FiAlertTriangle,
    FiBriefcase,
    FiCalendar,
    FiBox,
    FiCode,
    FiChrome,
    FiKey,
    FiMail,
    FiPlay } from 'react-icons/fi'
import { IconType } from 'react-icons/lib'
export const Icons: Record<string, IconType> = {
    FiArchive: FiArchive,
    FiBookOpen: FiBookOpen,
    FiBook: FiBook,
    FiBookmark: FiBookmark,
    FiCoffee: FiCoffee,
    FiFilm: FiFilm,
    FiHeadphones: FiHeadphones,
    FiHeart: FiHeart,
    FiLock: FiLock,
    FiShoppingBag: FiShoppingBag,
    FiShoppingCart: FiShoppingCart,
    FiAlertTriangle: FiAlertTriangle,
    FiBriefcase: FiBriefcase,
    FiCalendar: FiCalendar,
    FiBox: FiBox,
    FiCode: FiCode,
    FiChrome: FiChrome,
    FiKey: FiKey,
    FiMail: FiMail,
    FiPlay: FiPlay
}